workflows:
  ios-beta:
    name: Build and submit internal test release
    max_build_duration: 15
    environment:
      groups:
        - secrets
      flutter: stable

    scripts:
      - name: Install Shorebird
        script: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV

      - name: Run Fastlane iOS Beta
        script: |
          set -e
          cd ios
          bundle install
          bundle exec fastlane ios beta

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Runner.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      slack:
        notify_on_build_start: true
        channel: "#cicd-all"
        notify:
          failure: true
          success: true
