workflows:
  ios-beta:
    name: Build and submit internal test release
    max_build_duration: 15
    environment:
      groups:
        - secrets
      flutter: stable
    scripts:
#      - name: Set project environment variables
#        script: |
#          cat .env >> $CM_ENV
#      - name: Install pods
#        script: |
#          find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Run Fastlane ios-beta
        script: |
          set -e
          set -x
          cd ios
          bundle install
          bundle exec fastlane ios beta
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      slack:
        notify_on_build_start: true
        channel: "#cicd-all"
        notify:
          failure: true
          success: true
