workflows:
  ios-beta:
    name: Build and submit internal test release
    max_build_duration: 15
    environment:
      groups:
        - secrets
      flutter: stable
    scripts:
#      - name: Set project environment variables
#        script: |
#          cat .env >> $CM_ENV
      - name: Set up Ruby and Fastlane
        script: |
          pushd ios
          gem install bundler
          bundle install
          popd
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Run 'beta' fastlane
        script: |
          pushd ios
          bundle exec fastlane ios beta
          popd
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      slack:
        notify_on_build_start: true
        channel: "#cicd-all"
        notify:
          failure: true
          success: true
