// Placeholder for the flavor-specific Firebase configuration.
//
// The real file is generated by `flutterfire config`
// (see update-flutterfire-config.sh), which is run by setup.sh
// and by the 'update-flutterfire' Codemagic workflow.
// Until then, the app can be built, but not started.
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => throw UnsupportedError(
    'The project is not configured yet; run ./setup.sh',
  );
}
