# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# NON-EDITABLE WHEN LIVE:
# - name,
# - subtitle,
# - categories,
# - keywords, and
# - Apple TV privacy policy

# app_languages=['en-US']
app_languages=['en-US','ru']
puts "Languages to process: #{app_languages.join(', ')}"

languages(app_languages)

support_url(app_languages.to_h { |lang| [lang, 'https://sneakybird.app'] })

copyright "#{Time.now.year} #{ENV['APP_STORE_COMPANY_NAME']}"

# broken
precheck_include_in_app_purchases false

automatic_release true
phased_release true
app_rating_config_path 'fastlane/content-rating.json'
screenshots_path 'fastlane/screenshots'

# Contact information for the app review team
# metadata/review_information/
app_review_information(
  first_name: ENV['DEV_FIRST_NAME'],
  last_name: ENV['DEV_LAST_NAME'],
  phone_number: ENV['DEV_PHONE'],
  email_address: ENV['DEV_EMAIL'],
  # demo_user: "",
  # demo_password: "",
  # notes: "",
)

# https://developer.apple.com/app-store/categories/
# primary_category 'BOOKS'
# primary_category 'BUSINESS'
# primary_category 'DEVELOPER_TOOLS'
# primary_category 'EDUCATION'
# primary_category 'ENTERTAINMENT'
# primary_category 'FINANCE'
# primary_category 'FOOD_AND_DRINK'
# primary_category 'GAMES'
# primary_category 'GRAPHICS_AND_DESIGN'
# primary_category 'HEALTH_AND_FITNESS'
# primary_category 'LIFESTYLE'
# primary_category 'MAGAZINES_AND_NEWSPAPERS'
# primary_category 'MEDICAL'
# primary_category 'MUSIC'
# primary_category 'NAVIGATION'
# primary_category 'NEWS'
# primary_category 'PHOTO_AND_VIDEO'
# primary_category 'PRODUCTIVITY'
# primary_category 'REFERENCE'
# primary_category 'SHOPPING'
# primary_category 'SOCIAL_NETWORKING'
# primary_category 'SPORTS'
# primary_category 'STICKERS'
# primary_category 'TRAVEL'
# primary_category 'UTILITIES'
# primary_category 'WEATHER'

# primary_first_sub_category 'GAMES_ACTION'
# primary_first_sub_category 'GAMES_ADVENTURE'
# primary_first_sub_category 'GAMES_BOARD'
# primary_first_sub_category 'GAMES_CARD'
# primary_first_sub_category 'GAMES_CASINO'
# primary_first_sub_category 'GAMES_CASUAL'
# primary_first_sub_category 'GAMES_FAMILY'
# primary_first_sub_category 'GAMES_MUSIC'
# primary_first_sub_category 'GAMES_PUZZLE'
# primary_first_sub_category 'GAMES_RACING'
# primary_first_sub_category 'GAMES_ROLE_PLAYING'
# primary_first_sub_category 'GAMES_SIMULATION'
# primary_first_sub_category 'GAMES_SPORTS'
# primary_first_sub_category 'GAMES_STRATEGY'
# primary_first_sub_category 'GAMES_TRIVIA'
# primary_first_sub_category 'GAMES_WORD'
# primary_first_sub_category 'STICKERS_ANIMALS'
# primary_first_sub_category 'STICKERS_ART'
# primary_first_sub_category 'STICKERS_CELEBRATIONS'
# primary_first_sub_category 'STICKERS_CELEBRITIES'
# primary_first_sub_category 'STICKERS_CHARACTERS'
# primary_first_sub_category 'STICKERS_EATING_AND_DRINKING'
# primary_first_sub_category 'STICKERS_EMOJI_AND_EXPRESSIONS'
# primary_first_sub_category 'STICKERS_FASHION'
# primary_first_sub_category 'STICKERS_GAMING'
# primary_first_sub_category 'STICKERS_KIDS_AND_FAMILY'
# primary_first_sub_category 'STICKERS_MOVIES_AND_TV'
# primary_first_sub_category 'STICKERS_MUSIC'
# primary_first_sub_category 'STICKERS_PEOPLE'
# primary_first_sub_category 'STICKERS_PLACES_AND_OBJECTS'
# primary_first_sub_category 'STICKERS_SPORTS_AND_ACTIVITIES'

# primary_second_sub_category

# secondary_category
# secondary_first_sub_category
# secondary_second_sub_category


# empty string ("", not null) to remove the existing attachment file
# app_review_attachment_file: "./readme.txt"

# Must be a hash.
# This is used as the last step for the deployment process,
# where you define if you use third party content or use encryption.
# https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb
submission_information({

  add_id_info_uses_idfa: false,

# Ad ID Info - Serves ads
  add_id_info_serves_ads: false,

# Ad ID Info - Tracks actions
  add_id_info_tracks_action: false,

# Ad ID Info - Tracks installs
  add_id_info_tracks_install: false,

# Content Rights - Contains third party content
  content_rights_contains_third_party_content: false,

# Content Rights - Has rights of content
  content_rights_has_rights: false,

# Export Compliance - Available on French Store
  export_compliance_available_on_french_store: false,

# Export Compliance - Contains proprietary cryptography
  export_compliance_contains_proprietary_cryptography: false,

# Export Compliance - Contains third-party cryptography
  export_compliance_contains_third_party_cryptography: false,

# Export Compliance - Is exempt
# export_compliance_is_exempt: false,

# Export Compliance - Uses encryption
  export_compliance_uses_encryption: false,

# String: Export Compliance - App type

# export_compliance_app_type: ''

# Export Compliance - Encryption Updated
  export_compliance_encryption_updated: false,

# Export Compliance - Compliance Required
  export_compliance_compliance_required: false,

# String: Export Compliance - Platform

# export_compliance_platform: '',

# Not Yet Implemented: Export Compliance - CCAT File

# export_compliance_ccat_file: NA
})

# Trade Representative Contact information for Korean App Store
# (tbd: check if applicable to individual developers)
# metadata/trade_representative_contact_information/
# trade_representative_contact_information(
#   first_name: "",
#   last_name: "",
#   address_line1: "",
#   address_line2: "",
#   address_line3: null,
#   city_name: "",
#   state: "",
#   country: "",
#   postal_code: "",
#   phone_number: "+",
#   email_address: "",
#   is_displayed_on_app_store: true
# )

overwrite_screenshots true
skip_app_version_update true
force true
