# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    if ENV['APP_STORE_CONNECT_PRIVATE_KEY']
      # CI
      app_store_connect_api_key(
        key_id: ENV['APP_STORE_CONNECT_KEY_IDENTIFIER'],
        issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
        key_content: ENV['APP_STORE_CONNECT_PRIVATE_KEY'])
    else
      # Dev workstation
      ENV['FASTLANE_PASSWORD'] = File.read(ENV['ITUNES_PASSWORD_PATH']).strip
      app_store_connect_api_key(
        key_id: ENV['APP_STORE_CONNECT_KEY_IDENTIFIER'],
        issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
        key_filepath: ENV['APP_STORE_CONNECT_PRIVATE_KEY_PATH'])
    end
  end

  lane :create do
    produce(
      company_name: ENV['APP_STORE_COMPANY_NAME'],
      app_name: ENV['APP_NAME_DISPLAY'],
      language: ENV['PRIMARY_APP_LANGUAGE'],
      sku: ENV['APP_TIMESTAMP'],
      app_version: '1.0',
    )

  end

  lane :deploy_meta do
    # generate screenshots
    deliver
  end

  lane :build_flutter do
    build_app
  end

  lane :deploy_testflight do
    upload_to_testflight
  end

  lane :deploy_appstore do

  end

end
