# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

def flavor
  ENV['FLUTTER_FLAVOR'] || abort("Flutter flavor (FLUTTER_FLAVOR) is not set")
end

def build_aab(build_name, build_number, build_stamp, patch)
  sync_app_screen_label

  Dir.chdir("../..") do

    quick_build = ENV['QUICK_BUILD'] == 'true'
    shorebird_initialised = File.exist?('shorebird.yaml')

    unless quick_build
      # Quality check
      sh 'flutter pub get'
      sh 'flutter analyze'
      sh 'flutter test -x screenshots'
    end

    if patch
      unless shorebird_initialised
        UI.user_error!('Can not build a patch: Shorebird integration has not been configured.')
      end
      command = 'shorebird patch android'
    else
      command = quick_build || !shorebird_initialised ? "flutter build aab" : "shorebird release android"
    end

    sh <<~COMMAND
      #{command} \
        --flavor #{flavor} \
        -t lib/main_#{flavor}.dart \
        --split-debug-info=build/app/outputs/symbols \
        --build-name=#{build_name} \
        --build-number=#{build_number} \
        --dart-define-from-file=.env.runtime.#{flavor} \
        --dart-define=SENTRY_DIST=#{ENV['SENTRY_DSN'] ? build_stamp : ''}
    COMMAND
  end
end

def release_patch(track)
  build_name = YAML.load_file('../../pubspec.yaml')['version']

  version_codes = google_play_track_version_codes(
    track: track,
  )

  if version_codes.empty?
    raise "No version codes found in Play Store for '#{track}' track!"
  end

  build_number = version_codes[0]

  sentry_dist = "android-#{build_number}"

  build_aab(build_name, build_number, sentry_dist, true)
end

def sync_app_screen_label
  Dir.chdir("..") do
    app_screen_label = CGI.escapeHTML(ENV['APP_SCREEN_LABEL'])
    manifest_path = "app/src/main/AndroidManifest.xml"

    file_content = File.read(manifest_path)
    updated_content = file_content.sub(/android:label=".*?"/, "android:label=\"#{app_screen_label}\"")

    File.write(manifest_path, updated_content)
  end
end

platform :android do

  before_all do
    # ensure_git_status_clean(
    #   show_uncommitted_changes: true,
    # )
    if ENV['SENTRY_PROJECTS_ADMIN_TOKEN_PATH']
      # Local dev env
      ENV['SENTRY_AUTH_TOKEN'] = File.read(ENV['SENTRY_CI_TOKEN_PATH'])
      ENV['SHOREBIRD_TOKEN'] = File.read(ENV['SHOREBIRD_TOKEN_PATH'])
    end
  end

  desc "Builds an integration test bundle and runs it on Test Lab"
  lane :test_lab do
    Dir.chdir("..") do
      sh 'flutter build apk --flavor dev -t lib/main_dev.dart --dart-define-from-file=.env.runtime.dev'
      sh './gradlew app:assembleAndroidTest'
      sh './gradlew app:assembleDebug -Ptarget=integration_test/all_tests.dart'
      sh "gcloud --quiet config set project #{ENV['APP_ID_SLUG']}"
      sh <<~COMMAND
        gcloud firebase test android run \
          --timeout 15m \
          --type instrumentation \
          --app ../build/app/outputs/apk/debug/app-debug.apk \
          --test ../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --results-bucket=gs://#{ENV['TEST_LAB_BUCKET_NAME']} \
          --results-dir=test-lab-android-$(date +%Y%m%d-%H%M)
      COMMAND
    end
  end

  desc "Copies the app screen label from .env.build file to Android manifest"
  lane :update_app_screen_label do
    sync_app_screen_label
  end

  desc "Builds and uploads a new internal release"
  lane :internal do
    build_name = YAML.load_file('../../pubspec.yaml')['version']

    now = Time.now.getlocal(Time.zone_offset(ENV['TZ'] || 'UTC'))
    build_number = "#{now.year - 2020}#{now.strftime('%m%d%H%M')}"

    build_stamp = "android-#{build_number}"

    # Build an application bundle
    build_aab(build_name, build_number, build_stamp, false)

    # Generate screenshots
    Dir.chdir("../..") do
      sh "flutter test --update-goldens --tags=screenshots-android"
    end

    # Prepare App page graphics
    sh 'cp -rf ../../assets/dev/android/* metadata/android'

    # Prepare debug symbols for native libraries
    native_symbols_path = 'build/app/intermediates/merged_native_libs/release/out/lib'
    Dir.chdir("../../#{native_symbols_path}") do
      sh "zip -q -r symbols.zip ."
    end

    # Prepare changelog
    changelog = read_changelog(changelog_path: '../CHANGELOG.md')
    FileUtils.mkdir_p("metadata/android/en-US/changelogs")
    File.write("metadata/android/en-US/changelogs/default.txt", changelog)

    # Upload
    supply(
      track: 'internal',
      release_status: "draft",
      track_promote_release_status: 'draft',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      mapping_paths: %W[../#{native_symbols_path}/symbols.zip ../build/app/outputs/mapping/release/mapping.txt],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      changes_not_sent_for_review: true,
    )

    if ENV['SENTRY_DSN'] && !ENV['SENTRY_DSN'].empty?
      Dir.chdir("../..") do
        sh "dart run sentry_dart_plugin --sentry-define=dist=#{build_stamp}"
      end
    end

    add_git_tag(
      tag: "#{build_name}+#{build_stamp}",
    )

    push_git_tags
  end

  desc "Releases a Shorebird patch for the latest internal build"
  lane :patch_internal do
    release_patch('internal')
  end
end
